name: biliup-test

on:
  workflow_dispatch:
    inputs:
      SOURCE_TAGS:
        description: 'Source Repositry Branch/Commit/Tag'
        default: 'master'
      DEST_TAGS:
        description: 'Destination Docker Tag (multiple with comma)'
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Tags
        run: |
          echo "DEST_TAGS_JSON=$(echo '[\"'${{ github.event.inputs.DEST_TAGS }}'\"' | sed 's/,/\",\"/g')]" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/biliup/biliup.git#${{ github.event.inputs.SOURCE_TAGS }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.workflow }}:${{ fromJSON(env.DEST_TAGS_JSON) }}
